Repository Arquisoft/wichat_es6a, pull requests merged in 2025-03, with the labels that each got.

#74 Added that user statistics are obtained from the database dynamically
  webapp/src/components/StatisticsWindow.js
Labels: User Inteface

#78 Dinamic Statistics window
  docker-compose.yml
  historyservice/.dockerignore
  historyservice/Dockerfile
  historyservice/history-model.js
  historyservice/history-stats-service.js
  historyservice/package-lock.json
  historyservice/package.json
  historyservice/user-model.js
  webapp/src/components/StatisticsWindow.js
Labels: User Inteface, Database

#79 LLM-service is now avaiable and runing correctly.
  llmservice/llm-service.js
Labels: LLM

#85 Llm genarate hint service
  llmservice/llm-service.js
Labels: LLM

#100 Wikidata info
  docker-compose.yml
  gatewayservice/gateway-service.js
  llmservice/llm-service.js
  webapp/package-lock.json
  webapp/src/components/GameWindow.js
  webapp/src/components/home.js
  wikidataservice/Dockerfile
  wikidataservice/package-lock.json
  wikidataservice/package.json
  wikidataservice/wikidata-service.js
  wikidataservice/wikidataConnection.js
  wikidataservice/wikidataQueries.js
Labels: enhancement

#87 Documentación risks and technical debt
  docs/src/11_technical_risks.adoc
Labels: documentation

#90 Update ocumentation 04 Solution Strategy
  docs/src/04_solution_strategy.adoc
Labels: documentation

#108 Functional game
  llmservice/llm-service.js
  webapp/package-lock.json
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
Labels: User Inteface, Database, LLM, Backend

#114 2. Addes complex points system to the game object
  webapp/src/App.js
  webapp/src/components/EndGameWindow.js
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
  webapp/src/components/Navbar.js
  webapp/src/components/ScoreWindow.js
  webapp/src/components/StatisticsWindow.js
  webapp/src/components/home.js
  wikidataservice/package.json
Labels: User Inteface, Backend

#121 add 30-second timer per question and update timeout behavior
  gatewayservice/Dockerfile
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
Labels: User Inteface, Backend

#131 Services tests -> Wikidata and LLM
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  wikidataservice/package-lock.json
  wikidataservice/package.json
  wikidataservice/wikidata-service.js
  wikidataservice/wikidata-service.test.js
  wikidataservice/wikidataConnection.js
  wikidataservice/wikidataQueries.js
Labels: LLM, Backend, Tests

#138 Game Window Redisign
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/ChatClues.js
  webapp/src/components/GameWindow.js
  webapp/src/components/QuestionTimer.css
  webapp/src/components/QuestionTimer.jsx
Labels: User Inteface
