Repository Arquisoft/wichat_es6a, pull requests merged in 2025-04, with the labels that each got.

#151 User Session System Implementation and Statistics Service Improvements
  historyservice/history-stats-service.js
  historyservice/package-lock.json
  historyservice/package.json
  llmservice/config/database.js
  llmservice/models/history-model.js
  users/authservice/package-lock.json
  users/authservice/package.json
  webapp/public/profileImg.png
  webapp/src/components/Login.js
  webapp/src/components/Navbar.js
  webapp/src/components/StatisticsWindow.js
Labels: bug, User Inteface, Database, Backend

#152 Fixed bugs and errors in endGameWindow
  webapp/src/components/EndGameWindow.js
Labels: bug

#156 Redisign Home UI
  webapp/src/components/Navbar.js
  webapp/src/components/home.js
Labels: User Inteface

#157 Pre-generate question images at game start
  llmservice/llm-service.js
  llmservice/package-lock.json
  llmservice/package.json
  package-lock.json
  package.json
  webapp/src/components/Game.js
  webapp/src/components/GameOptions.js
  webapp/src/components/GameWindow.js
Labels: User Inteface, LLM, Backend

#173 Addition of difficulty levels
  llmservice/llm-service.js
  webapp/src/components/Game.js
  webapp/src/components/GameOptions.js
  webapp/src/components/GameWindow.js
Labels: User Inteface, Backend

#176 175 add more system information to metrics and create new grafana dashboard
  gatewayservice/gateway-service.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/main-dashboard.json
  llmservice/llm-service.js
  users/authservice/auth-service.js
  users/userservice/user-service.js
Labels: Monitoring

#180 Replace Gemini image generation with Wikidata images
  llmservice/llm-service.js
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
  wikidataservice/models/wikidata-entry-model.js
  wikidataservice/wikidataCacheService.js
  wikidataservice/wikidataQueries.js
Labels: Database, Backend

#181 Add limited-use lifeline system: 50/50, Ask Chat, and Hint
  webapp/src/components/ChatClues.js
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
Labels: enhancement

#184 183 modify the navigation bar component to hide the statistics option if the user is not logged in
  webapp/src/components/GameWindow.js
  webapp/src/components/Navbar.js
Labels: bug, User Inteface

#187 186 fix the links for the play again and start playing buttons
  webapp/src/components/EndGameWindow.js
  webapp/src/components/home.js
Labels: User Inteface

#189 Upgrade the game difficult selection
  webapp/src/components/GameOptions.js
Labels: User Inteface

#192 Implemented a new shuffle algorithm for the answer choices.
  webapp/src/components/Game.js
Labels: Backend

#201 195 upgrade statistics window
  historyservice/history-stats-service.js
  llmservice/models/history-model.js
  webapp/src/components/EndGameWindow.js
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
  webapp/src/components/StatisticsWindow.js
Labels: User Inteface, Backend

#202 199 fix the chat 400 error when you use the chat to talk
  llmservice/llm-service.js
  webapp/src/components/ChatClues.js
  webapp/src/components/GameWindow.js
Labels: bug, LLM, Backend

#221 Update Interface Login.test.js
  webapp/src/components/Login.test.js
Labels: Tests

#222 197 add all services state to garafana graphics
  gatewayservice/gateway-service.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/main-dashboard.json
  historyservice/history-stats-service.js
  users/questionsService/question-history-service.js
  wikidataservice/wikidata-service.js
Labels: Monitoring

#224 Gateway service test updated
  gatewayservice/gateway-service.test.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
Labels: Backend, Tests

#227 226 document services with openapi specifications
  gatewayservice/openapi.yaml
  historyservice/history-stats-service.js
  historyservice/openapi.yaml
  historyservice/package-lock.json
  historyservice/package.json
  llmservice/llm-service.js
  llmservice/openapi.yaml
  llmservice/package-lock.json
  llmservice/package.json
  users/authservice/auth-service.js
  users/authservice/openapi.yaml
  users/authservice/package-lock.json
  users/authservice/package.json
  users/questionsService/openapi.yaml
  users/questionsService/package-lock.json
  users/questionsService/package.json
  users/questionsService/question-history-service.js
  users/userservice/openapi.yaml
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-service.js
  wikidataservice/openapi.yaml
  wikidataservice/package-lock.json
  wikidataservice/package.json
  wikidataservice/wikidata-service.js
Labels: documentation

#228 210 UI testing
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Login.test.js
  webapp/src/components/StatisticsWindow.js
  webapp/src/components/StatisticsWindow.test.js
  webapp/src/components/navBar.test.js
  webapp/src/editProfileWindow.test.js
Labels: User Inteface, Tests

#237 home window tests implementation
  webapp/src/components/home.test.js
Labels: Tests

#241 Coverage bug
  .github/workflows/build.yml
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  llmservice/llm-service.test.js
  llmservice/package.json
  sonar-project.properties
  users/questionsService/question-history-service.test.js
  users/userservice/package.json
  users/userservice/user-service.test.js
  webapp/src/components/navBar.test.js
Labels: bug, Tests

#240 gameOptions window tests implementation
  webapp/src/components/gameOptions.test.js
Labels: Tests

#242 EndGameWindow tests implementation
  webapp/src/components/EndGameWindow.test.js
Labels: Tests

#245 Increased navbar text coverage
  webapp/src/components/navBar.test.js
Labels: User Inteface, Tests

#249 improved statisticsWindow tests
  webapp/src/components/StatisticsWindow.test.js
Labels: Tests

#251 QuestionTimer tests implementation
  webapp/src/components/QuestionTimer.test.js
Labels: Tests

#254 248 increase testing coverage
  webapp/src/components/ChatClues.js
  webapp/src/components/ChatClues.test.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
Labels: User Inteface, Tests

#255 finished wikidata tests
  wikidataservice/wikidataCacheService.test.js
  wikidataservice/wikidataQueries.test.js
Labels: Tests
