Repository Arquisoft/wichat_es6a, pull requests merged in 2025-05, with the labels that each got.

#259 248 increase testing coverage
  sonar-project.properties
  webapp/src/components/EndGameWindow.test.js
Labels: User Inteface, Tests

#260 248 increase testing coverage
  llmservice/database.test.js
  llmservice/hitory-model.test.js
  llmservice/package-lock.json
  llmservice/package.json
  llmservice/questions-model.test.js
  llmservice/stats-model.test.js
  llmservice/user-model.test.js
Labels: Backend, Tests

#263 Game window UI tests
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
  webapp/src/components/GameWindow.test.js
  webapp/src/components/StatisticsWindow.test.js
Labels: Tests

#265 LoadTests report and test.java
  docs/loadTests/RegisterUser.java
  docs/loadTests/index.html
  docs/loadTests/js/all_sessions.js
  docs/loadTests/js/assertions.xml
  docs/loadTests/js/bootstrap.min.js
  docs/loadTests/js/ellipsis.js
  docs/loadTests/js/gatling.js
  docs/loadTests/js/global_stats.json
  docs/loadTests/js/highcharts-more.js
  docs/loadTests/js/highstock.js
  docs/loadTests/js/jquery-3.5.1.min.js
  docs/loadTests/js/menu.js
  docs/loadTests/js/stats.js
  docs/loadTests/js/stats.json
  docs/loadTests/js/theme.js
  docs/loadTests/js/unpack.js
  docs/loadTests/req_login-user-186742370.html
  docs/loadTests/req_preflight-reque--248034440.html
  docs/loadTests/req_preflight-reque--268164044.html
  docs/loadTests/req_register-user--650051800.html
  docs/loadTests/simulation.log
  docs/loadTests/style/bootstrap.min.css
  docs/loadTests/style/close.svg
  docs/loadTests/style/executions.svg
  docs/loadTests/style/expand.svg
  docs/loadTests/style/favicon.ico
  docs/loadTests/style/fullscreen.svg
  docs/loadTests/style/logo-dark.svg
  docs/loadTests/style/logo-enterprise-dark.svg
  docs/loadTests/style/logo-enterprise-light.svg
  docs/loadTests/style/logo-light.svg
  docs/loadTests/style/sort-down.svg
  docs/loadTests/style/sort-up.svg
  docs/loadTests/style/sort.svg
  docs/loadTests/style/style.css
Labels: Tests

#267 Add coverage tests
  llmservice/generate-questions.test.js
  llmservice/getRandomEntriesAuxiliaryFunction.test.js
  llmservice/llm-service-AuxiliaryFunctions.test.js
  llmservice/llm-service.js
  llmservice/mm.test.js
  llmservice/package-lock.json
  llmservice/package.json
  llmservice/parseJSONAuxFunction.test.js
  sonar-project.properties
  wikidataservice/wikidataConnection.js
Labels: Backend, Tests

#268 Documentation arquitecture decisions
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#269 Add coverage tests
  webapp/package.json
  webapp/src/components/EndGameWindow.js
  webapp/src/components/EndGameWindow.test.js
  webapp/src/components/editProfileWindow.js
  webapp/src/components/editProfileWindowAuxFunc.test.js
Labels: User Inteface, Tests

#281 Update 11_technical_risks.adoc
  docs/src/11_technical_risks.adoc
Labels: documentation

#276 Update 04_solution_strategy.adoc
  docs/src/04_solution_strategy.adoc
Labels: documentation

#278 Documentation runtime view
  docs/images/sequence-answering-question.png
  docs/images/sequence-ask-hint.png
  docs/images/sequence-password-change.png
  docs/images/sequence-question-generation.png
  docs/images/sequence-user-login.png
  docs/images/sequence-user-registration.png
  docs/src/06_runtime_view.adoc
Labels: documentation

#283 Update 04_solution_strategy.adoc
  docs/src/04_solution_strategy.adoc
Labels: documentation

#287 Profile pictures are now allowed in more formats than just PNG
  users/userservice/user-service.js
  webapp/src/components/AllQuestionsWindow.js
  webapp/src/components/QuestionHistoryWindow.js
  webapp/src/components/QuestionHistoryWindow.test.js
Labels: User Inteface, Backend

#294 improved usability of clues and chat
  webapp/src/components/ChatClues.js
  webapp/src/components/ChatClues.test.js
  webapp/src/components/GameWindow.js
Labels: User Inteface, usability

#299 Chat scroll
  webapp/src/components/ChatClues.js
Labels: User Inteface, usability

#306 improve the home window
  webapp/public/info-window/comodin-50-50.png
  webapp/public/info-window/comodin-pista.png
  webapp/public/info-window/comodin-preguntar-IA.png
  webapp/public/info-window/comodines.png
  webapp/public/info-window/dificultad-dificil.png
  webapp/public/info-window/dificultad-facil.png
  webapp/public/info-window/dificultad-media.png
  webapp/public/info-window/info-introducction.png
  webapp/public/info-window/modos-juego.png
  webapp/public/info-window/racha-aciertos.png
  webapp/src/App.js
  webapp/src/components/HowToPlayWindow.js
  webapp/src/components/HowToPlayWindow.test.js
  webapp/src/components/home.js
  webapp/src/components/home.test.js
Labels: User Inteface, Tests

#303 Documentation arquitecture decisions
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#312 Deploy over ssh
  .github/workflows/release.yml
  README.md
  docs/src/09_architecture_decisions.adoc
  historyservice/history-stats-service.js
  users/userservice/user-service.js
  webapp/src/components/AddUser.js
  webapp/src/components/AllQuestionsWindow.js
  webapp/src/components/Game.js
  webapp/src/components/Login.js
  webapp/src/components/Navbar.js
  webapp/src/components/StatisticsWindow.js
  webapp/src/components/editProfileWindow.js
Labels: deployment

#313 297 deploy the application using GitHub actions
  .github/workflows/release.yml
  historyservice/history-stats-service.js
  questionsService/question-history-service.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/authservice/package.json
  users/userservice/user-service.js
  webapp/e2e/jest.config.js
  webapp/e2e/steps/01-register-form.steps.js
  webapp/e2e/steps/02-login-form.steps.js
  webapp/e2e/steps/03-game-window-form.steps.js
  webapp/e2e/steps/04-stats-access.steps.js
  webapp/e2e/steps/05-questions-access.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/src/components/Game.js
  webapp/src/components/GameWindow.js
  webapp/src/components/Login.js
  webapp/src/components/Navbar.js
  webapp/src/components/editProfileWindow.js
  webapp/src/index.js
  wikidataservice/wikidata-service.js
Labels: deployment

#316 315 add tests documentation
  docs/src/13_test.adoc
Labels: documentation
