Repository Arquisoft/wichat_es6a, pull requests merged in 2025-02, with the labels that each got.

#21 Documentación inicial "Solution Strategy"
  docs/src/04_solution_strategy.adoc
Labels: documentation

#22 Documentación inicial "Architecture Decisions"
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#23 Documentación inicial: risks and technical debt
  docs/src/11_technical_risks.adoc
Labels: documentation

#24 Documentación inicial: Introducción y objetivos
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#35 Documentation cross cutting concepts
  docs/images/Cross-cutting_Concepts.jpg
  docs/src/08_concepts.adoc
Labels: documentation

#36 Translation to English
  docs/src/01_introduction_and_goals.adoc
Labels: documentation

#37 Documentación constraints
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#41 Added message that runtime view will be updated later
  docs/src/06_runtime_view.adoc
Labels: documentation

#33 Translation into English of solution strategy
  docs/src/04_solution_strategy.adoc
Labels: documentation

#40 Translation and enhancement of Architectural Decisions
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#43 Completed Documentacion_DeploymentView
  docs/src/07_deployment_view.adoc
Labels: documentation

#47 Fixed issue in the documentation (Crosscutting Concepts)
  docs/src/11_technical_risks.adoc
Labels: bug

#62 Statistics window 1.0
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/StatisticsWindow.js
  webapp/src/index.js
Labels: User Inteface

#70 Database initial
  .gitignore
  docker-compose.yml
  users/historyservice/history-model.js
Labels: Database
